### PR TITLE
Amend project data to include package metadata and include build instructions in readme

### PR DESCRIPTION
**Pull request by martijnhoekstra**
I'm working on CI through appveyor, but I'm hitting some problems (and the "fiddle with a yaml file, push the branch, see what the CI does with it, determine what the problem is, fiddle with it some more" workflow is really bothersome and slow).

Because I'm taking so long with CI integration, I want to propose to publish a package manually.

This PR includes building instructions in the READEME.md which you can use to publish a package. With this toolchain, I think the need (and applicability) of the bin/dll build script is gone, so I've removed that in this PR as well. I've only tested buiding on Windows machines, so checking whether the instructions hold on other platforms is likely worthwhile.

The metadata for the package comes from the csproj file, particularly the properties in `<PropertyGroup Label="Packaging">`

Packages are uniquely defined by their package ID in the PackageID element. Changing the package ID means it's seen as a different package. Changing the case of the package ID means the package is more or less hopelessly broken (see: http://adamralph.com/2015/03/04/nuget-gallery-casing-woes/). The "latest version" is determined by the version number according to SemVer.

That means that you're free to change any meta-data when publishing a new version after release without any permanent technical consequences, with the exception of Package ID (which should never change) and Version (which should always change to be higher than the previous version according to SemVer), so take particular care reviewing those porperties

Documentation on manual publishing to nuget.org can be found on https://docs.nuget.org/ndocs/create-packages/publish-a-package

### CODE REVIEW

**Comment by tonymorris** [comment]
What is the conflict?

**Comment by martijnhoekstra** [comment]
no idea, trying to work it out - I think I mis-gitted

**Comment by martijnhoekstra** [comment]
rebased on a stale upstream. Rebasing again now

**Comment by martijnhoekstra** [comment]
much cleaner now

**Pull request merged**
